import ROOT

ROOT.gStyle.SetOptTitle(0)
ROOT.gStyle.SetOptStat(0)
ROOT.gStyle.SetCanvasColor(0)
ROOT.gStyle.SetPadColor(0)
ROOT.gStyle.SetTitleFillColor(0)
ROOT.gStyle.SetTitleBorderSize(0)
ROOT.gStyle.SetFrameBorderMode(0)
ROOT.gStyle.SetPaintTextFormat(".0f")
ROOT.gStyle.SetLegendBorderSize(1)
ROOT.gStyle.SetLegendFillColor(ROOT.kWhite)
ROOT.gStyle.SetTitleFontSize(0.04)
ROOT.gStyle.SetPadTopMargin(0.05)
ROOT.gStyle.SetPadLeftMargin(0.11)
ROOT.gStyle.SetPadBottomMargin(0.12)
ROOT.gStyle.SetTitleXSize(0.05)
ROOT.gStyle.SetTitleYSize(0.05)
ROOT.gStyle.SetTextFont(42)
ROOT.gStyle.SetStatFont(42)
ROOT.gStyle.SetLabelFont(42,"x")
ROOT.gStyle.SetLabelFont(42,"y")
ROOT.gStyle.SetLabelFont(42,"z")
ROOT.gStyle.SetTitleFont(42,"x")
ROOT.gStyle.SetTitleFont(42,"y")
ROOT.gStyle.SetTitleFont(42,"z")
ROOT.gStyle.SetHistLineWidth(2)
ROOT.gStyle.SetGridColor(15)
ROOT.gStyle.SetPadGridX(1)
ROOT.gStyle.SetPadGridY(1)
ROOT.gStyle.SetHistMinimumZero(ROOT.kTRUE)
ROOT.gROOT.ForceStyle()

