#!/usr/bin/env python3

import argparse
cli = argparse.ArgumentParser(description='Compare active crontab to a file.')
cli.add_argument('file', type=str, help='crontab file to compare')
args = cli.parse_args()

import subprocess
with open(args.file,'r') as f:
    b = [ x.rstrip() for x in f.readlines() ]
    a = subprocess.check_output(['crontab','-l']).decode('utf-8').splitlines()
    import difflib, sys
    sys.exit(len([print(x) for x in difflib.unified_diff(a,b)]))

