io-services:
  reader:
    class: org.jlab.jnp.grapes.io.HipoFrameReader
    name: HipoFrameReader
  writer:
    class: org.jlab.jnp.grapes.io.HipoFrameWriter
    name: HipoFrameWriter
services:
#################################################### RF
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: RF
#################################################### DC
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: DCm
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: DCp
#################################################### FTOF
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: FTOFm
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: FTOFp
#################################################### HTCC
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: HTCCm
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: HTCCp
#################################################### CTOF
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: CTOF
#################################################### CND
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: CND
#################################################### FT
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: FTp
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: FTm
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: FTn
#################################################### BAND
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: BAND
####################################################
configuration:
  custom-names:
    1: rf 
    2: dc
    3: ftof
    4: htcc
    5: ctof
    6: cnd 
    7: ft 
    8: band
  io-services:
    writer:
      compression: 2
      filter: 1-RUN::config,RUN::rf,RF::.*,REC::Event,REC::Particle,REC::Scintillator-2-RUN::config,TimeBasedTrkg::TBHits,TimeBasedTrkg::TBSegments-3-RUN::rf,RUN::config,REC::Event,REC::Particle,REC::Track,REC::Scintillator,FTOF::*,TimeBasedTrkg::TBTracks-4-RUN::rf,RUN::config,REC::Event,REC::Particle,REC::Track,REC::Scintillator,REC::Cherenkov,HTCC::.*-5-RUN::rf,RUN::config,REC::Event,REC::Particle,REC::Track,REC::Scintillator,CTOF::*,CVTRec::Tracks-6-RUN::config,REC::Event,CVTRec::Tracks,CND::*-7-RUN::config,REC::Event,REC::Particle,FT::particles,FTCAL::*,FTHODO::*-8-RUN::config,REC::Event,REC::Particle,REC::Calorimeter,REC::Scintillator,REC::Track,BAND::*,RUN::scaler
  services:
#################################################### RF
    RF:
      id: 1
      forward: 11:X+:X-:Xn  
#################################################### DC
    DCm:
      id: 2
      forward: 1-:11:X+:X-:Xn
    DCp:
      id: 2
      forward: 1+:11:X+:X-:Xn  
#################################################### FTOF
    FTOFm:
      id: 3
      forward: 1-:11:X+:X-:Xn
    FTOFp:
      id: 3
      forward: 1+:11:X+:X-:Xn
#################################################### HTCC
    HTCCm:
      id: 4
      forward: 1-:11:X+:X-:Xn
    HTCCp:
      id: 4
      forward: 1+:11:X+:X-:Xn
#################################################### CTOF
    CTOF:
      id: 5
      forward: 11:X+:X-:Xn
      central: 1-:X+:X-:Xn
#################################################### CND
    CND:
      id: 6
      forward: 11:X+:X-:Xn
      central: 1-:X+:X-:Xn
#################################################### FT
    FTp:
      id: 7
      forward: 11:X+:X-:Xn
      tagger: 1+:X+:X-:Xn
    FTm:
      id: 7
      forward: 11:X+:X-:Xn
      tagger: 1-:X+:X-:Xn
    FTn:
      id: 7
      forward: 11:X+:X-:Xn
      tagger: 1n:X+:X-:Xn
    FTn:
      id: 7
      tagger: 2n:X+:X-:Xn      
#################################################### BAND
    BAND:
      id: 8
      forward: 11:X+:X-:Xn
      tagger: X+:X-:Xn
      central: X+:X-:Xn

mime-types:
  - binary/data-hipo-frame
