io-services:
  reader:
    class: org.jlab.jnp.grapes.io.HipoFrameReader
    name: HipoFrameReader
  writer:
    class: org.jlab.jnp.grapes.io.HipoFrameWriter
    name: HipoFrameWriter
services:
#################################################### RF
  - class: org.jlab.jnp.grapes.services.GenericWagon
    name: RF
configuration:
  io-services:
    writer:
      compression: 2
      filter: 1-RUN::config,RUN::rf,RF::.*,REC::Event,REC::Particle,REC::Scintillator
  services:
#################################################### RF
    RF:
      id: 1
      forward: 11:X+:X-:Xn

mime-types:
  - binary/data-hipo-frame
